backend:
  name: github
  repo: Youness-Ailal/ventrad
  branch: main
  squash_merges: true
  # open_authoring: true

logo_url: https://ventrad.co/_astro/logoText.BE-vSuzh.svg
publish_mode: simple
media_folder: public/images
public_folder: /images
site_url: "https://ventrad.co/"

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: blog/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - {
          label: "Publish",
          name: "isPublish",
          widget: "boolean",
          default: true,
        }
      - { label: "Photo", name: "photo", widget: "image" }
      - { name: body, label: Body, widget: markdown }

  - name: academy
    label: Academy
    delete: false
    editor:
      preview: false
    files:
      - name: academy
        label: Academy Page Content
        file: src/content/academy.md
        format: frontmatter
        fields:
          - { name: upperTitleEn, label: Upper Title (EN), widget: string }
          - { name: titleEn, label: Title (EN), widget: string }
          - { name: descriptionEn, label: Description (EN), widget: text }
          - { name: upperTitleFr, label: Upper Title (FR), widget: string }
          - { name: titleFr, label: Title (FR), widget: string }
          - { name: descriptionFr, label: Description (FR), widget: text }
          - name: videos
            label: HTML Embed Codes
            widget: list
            field:
              name: embedCode
              label: Embed Code
              widget: string
              hint: "Paste HTML embed code here from Wistia"

  - name: brands
    label: brands
    delete: false
    editor:
      preview: false
    files:
      - name: brands
        label: Brands images
        file: src/content/brands.md
        format: frontmatter
        fields:
          - name: brands
            label: Brands list
            widget: list
            field:
              name: Brandimage
              label: Brand image
              widget: image
