backend:
  name: github
  repo: Youness-Ailal/ventrad
  branch: main
  squash_merges: true
  # open_authoring: true

logo_url: https://ventrad.co/_astro/logoText.BE-vSuzh.svg
publish_mode: simple
media_folder: public/images
public_folder: /images
site_url: "https://ventrad.co/"

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: blog/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - {
          label: "Publish",
          name: "isPublish",
          widget: "boolean",
          default: true,
        }
      - { label: "Photo", name: "photo", widget: "image" }
      - { name: body, label: Body, widget: markdown }
